sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Shubhamgrd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Shubhamgrd/docker-react npm run test